spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedHeaders: "*" # 允许所有的请求头携带过来
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 用户微服务
        - id: user_route
          uri: lb://user #所有的请求都交给user服务处理
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1  #请求路径加前缀
            - name: RequestRateLimiter # 限流的名字底层默认的，不能更改
              args:
                key-resolver: "#{@ipKeyResolver}"     # SPEL表达式 与解析器限流bean当中的key对应
                redis-rate-limiter.burstCapacity: 3   # 允许一秒钟最大请求数    令牌桶容量
                redis-rate-limiter.replenishRate: 2  #希望允许每秒执行多少请求  填充速率

#  main:
#    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

  instance:
    prefer-ip-address: true