server:
  port: 9001
spring:
  application:
    name: oauth
  redis:
    host: 192.168.211.128
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/elevator_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  #    url: jdbc:mysql://192.168.211.132:3306/changgou_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
  #    username: root
  #    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false # 去除缓存
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.211.129:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost  # 前面不需要加点。cookie中自动添加【点】 设置一级域名即可
  cookieMaxAge: -1

jks:
  name: changgou.jks
  storepassword: changgou
  keypassword: changgou
  alias: changgou

logging:
  level:
    org.lufengxue.mapper: debug


#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8